version: "3"
services:
  py:
    container_name: pythocker
    image: pythocker:latest
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    